// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyATspPlS9bvGvFHBG7ltPffxJPTb9nrKu4',
//     appId: '1:1086951786644:web:d6e30351ecc239438ccc81',
//     messagingSenderId: '1086951786644',
//     projectId: 'flutter-login-app-73656',
//     authDomain: 'flutter-login-app-73656.firebaseapp.com',
//     storageBucket: 'flutter-login-app-73656.appspot.com',
//     measurementId: 'G-RZL3B3FTKS',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBcdin3yA_S-yt8_rahU10RXoBTqHyaLIE',
//     appId: '1:1086951786644:android:0246f6e58e5234a78ccc81',
//     messagingSenderId: '1086951786644',
//     projectId: 'flutter-login-app-73656',
//     storageBucket: 'flutter-login-app-73656.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBchrcooOl9_S0sA6nYWuDPrqbVPeVJRws',
//     appId: '1:1086951786644:ios:f66fab52adfd7b198ccc81',
//     messagingSenderId: '1086951786644',
//     projectId: 'flutter-login-app-73656',
//     storageBucket: 'flutter-login-app-73656.appspot.com',
//     iosClientId: '1086951786644-rg7233s8cg634519fi7b3ja7liojl8t2.apps.googleusercontent.com',
//     iosBundleId: 'com.example.newApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBchrcooOl9_S0sA6nYWuDPrqbVPeVJRws',
//     appId: '1:1086951786644:ios:f66fab52adfd7b198ccc81',
//     messagingSenderId: '1086951786644',
//     projectId: 'flutter-login-app-73656',
//     storageBucket: 'flutter-login-app-73656.appspot.com',
//     iosClientId: '1086951786644-rg7233s8cg634519fi7b3ja7liojl8t2.apps.googleusercontent.com',
//     iosBundleId: 'com.example.newApp',
//   );
// }
