// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1K49CT1gxYMbJ2IAgN4hAF6JvvX_d-Gw',
    appId: '1:725378900509:web:6d50e5ec3eccd123025cf4',
    messagingSenderId: '725378900509',
    projectId: 'phoneauth-5be1d',
    authDomain: 'phoneauth-5be1d.firebaseapp.com',
    storageBucket: 'phoneauth-5be1d.appspot.com',
    measurementId: 'G-NGD33KY9RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB54fIpMaKr3KYCzPdK3Oy8j5NEY34IS8',
    appId: '1:725378900509:android:93dbe3db7ad4c267025cf4',
    messagingSenderId: '725378900509',
    projectId: 'phoneauth-5be1d',
    storageBucket: 'phoneauth-5be1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrFSlDP-peSTP0xHKam6h9k4upiJW6eXk',
    appId: '1:725378900509:ios:fc68e109ed69aa18025cf4',
    messagingSenderId: '725378900509',
    projectId: 'phoneauth-5be1d',
    storageBucket: 'phoneauth-5be1d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrFSlDP-peSTP0xHKam6h9k4upiJW6eXk',
    appId: '1:725378900509:ios:fc68e109ed69aa18025cf4',
    messagingSenderId: '725378900509',
    projectId: 'phoneauth-5be1d',
    storageBucket: 'phoneauth-5be1d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
